apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeal
  labels:
    app: zeal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeal
  template:
    metadata:
      labels:
        app: zeal
    spec:
      containers:
      - name: zeal-web-service
        image: zeal/main:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zeal-service
spec:
  selector:
    app: zeal
  ports:
    - port: 10000
      targetPort: 8080