name: Delivery Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: ./scripts/build.sh
      - name: Stage Artifacts
        run: ./scripts/stage-artifacts.sh
      - name: Stage Reports
        run: ./scripts/stage-reports.sh
      - name: Upload Distribution Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: output/artifacts
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: output/reports

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Download Distribution Artifacts
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Stage zeal-main
        run: |
          mkdir -p zeal-main/target/
          cp dist/zeal-main-*.jar 
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: albanoj2/zeal
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}